# Generated by Django 5.1.2 on 2024-12-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointment_mentordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentordetails',
            name='avatar',
            field=models.ImageField(default='default_pp.jpg', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='mentordetails',
            name='college',
            field=models.TextField(default='Your college'),
        ),
        migrations.AlterField(
            model_name='mentordetails',
            name='description',
            field=models.TextField(default='Your description'),
        ),
        migrations.AlterField(
            model_name='mentordetails',
            name='specialization',
            field=models.TextField(default='Your Specialization'),
        ),
    ]
