# Generated by Django 5.1.2 on 2024-12-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mentordetails_avatar_alter_mentordetails_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordetails',
            name='cumulative_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
