# Generated by Django 5.1.2 on 2024-12-13 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_mentordetails_cumulative_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentordetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='mentordetails',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
