# Generated by Django 5.1.2 on 2024-12-13 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_mentordetails_id_alter_mentordetails_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordetails',
            name='avatar',
            field=models.ImageField(default='profile_pics/default_pp.jpg', upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('mentee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_fav', to=settings.AUTH_USER_MODEL)),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_fav', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('mentee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_review', to=settings.AUTH_USER_MODEL)),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
